name: Deploy some data to AWS Lightsail

on:
  push:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: File Creation
        run: timedatectl > temp_file
      - name: Write the ssh-key
        run: echo '${{ secrets.SSH_PRIVATE_KEY }}' > private_key
      - name: Verify file existence
        run: |
              cat temp_file
              wc private_key
      - name: Copy file to AWS
        run: scp -i private_key -o StrictHostKeyChecking=no temp_file ${{ vars.SERVER_HOSTNAME }}@${{ vars.SERVER_IP }}:${{ vars.SERVER_HOME }}
